### ISSUE TITLE
[gtc] Error 1

### ISSUE THREAD

**Issue by raonyguimaraes** [refresh-bio/GTC#2]
Hi there,

I'm trying to install GTC but it's not working:

make
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/bit_memory.cpp -o src/bit_memory.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/block_init_compressor.cpp -o src/block_init_compressor.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/buffered_bm.cpp -o src/buffered_bm.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/compressed_pack.cpp -o src/compressed_pack.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/compression_settings.cpp -o src/compression_settings.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/decompressor.cpp -o src/decompressor.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/end_compressor.cpp -o src/end_compressor.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/huffman.cpp -o src/huffman.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/main.cpp -o src/main.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/my_vcf.cpp -o src/my_vcf.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/samples.cpp -o src/samples.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/VCFManager.cpp -o src/VCFManager.o
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c include/cpp-mmf/memory_mapped_file.cpp -o include/cpp-mmf/memory_mapped_file.o
g++       -O3 -lm -lz -std=c++11 -lpthread -mpopcnt  -o gtc \
src/bit_memory.o \
src/block_init_compressor.o \
src/buffered_bm.o \
src/compressed_pack.o \
src/compression_settings.o \
src/decompressor.o \
src/end_compressor.o \
src/huffman.o \
src/main.o \
src/my_vcf.o \
src/samples.o \
src/VCFManager.o \
include/cpp-mmf/memory_mapped_file.o \
lib/libhts.a \
lib/libsdsl.a
src/main.o: In function `compress_input()':
main.cpp:(.text+0x4317): undefined reference to `pthread_create'
lib/libhts.a(hts.o): In function `decompress_peek':
/projects/temp/GTC/htslib-1.3.2/hts.c:141: undefined reference to `inflateInit2_'
/projects/temp/GTC/htslib-1.3.2/hts.c:144: undefined reference to `inflate'
/projects/temp/GTC/htslib-1.3.2/hts.c:147: undefined reference to `inflateEnd'
/projects/temp/GTC/htslib-1.3.2/hts.c:147: undefined reference to `inflateEnd'
lib/libhts.a(vcf.o): In function `vcf_hdr_read':
/projects/temp/GTC/htslib-1.3.2/vcf.c:1312: undefined reference to `gzopen'
lib/libhts.a(vcf.o): In function `ks_getc':
/projects/temp/GTC/htslib-1.3.2/vcf.c:49: undefined reference to `gzread'
lib/libhts.a(vcf.o): In function `vcf_hdr_read':
/projects/temp/GTC/htslib-1.3.2/vcf.c:1325: undefined reference to `gzclose'
lib/libhts.a(cram_io.o): In function `zlib_mem_deflate':
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:787: undefined reference to `deflateInit2_'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:801: undefined reference to `deflate'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:808: undefined reference to `deflate'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:813: undefined reference to `deflateEnd'
lib/libhts.a(cram_io.o): In function `itf8_decode_crc':
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:221: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:230: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:200: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:206: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:213: undefined reference to `crc32'
lib/libhts.a(cram_io.o):/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:548: more undefined references to `crc32' follow
lib/libhts.a(cram_io.o): In function `zlib_mem_inflate':
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:723: undefined reference to `inflateInit2_'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:736: undefined reference to `inflate'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:756: undefined reference to `inflateEnd'
lib/libhts.a(cram_io.o): In function `cram_read_block':
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:951: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:953: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:985: undefined reference to `crc32'
lib/libhts.a(cram_io.o): In function `cram_write_block':
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:1054: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:1059: undefined reference to `crc32'
lib/libhts.a(cram_io.o):/projects/temp/GTC/htslib-1.3.2/cram/cram_io.c:3123: more undefined references to `crc32' follow
lib/libhts.a(thread_pool.o): In function `t_pool_init':
/projects/temp/GTC/htslib-1.3.2/cram/thread_pool.c:457: undefined reference to `pthread_create'
lib/libhts.a(thread_pool.o): In function `t_pool_destroy':
/projects/temp/GTC/htslib-1.3.2/cram/thread_pool.c:647: undefined reference to `pthread_kill'
/projects/temp/GTC/htslib-1.3.2/cram/thread_pool.c:644: undefined reference to `pthread_join'
lib/libhts.a(zfio.o): In function `zfputs':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:80: undefined reference to `gzputs'
lib/libhts.a(zfio.o): In function `zfpeek':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:97: undefined reference to `gzungetc'
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:95: undefined reference to `gzgetc'
lib/libhts.a(zfio.o): In function `zfopen':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:165: undefined reference to `gzopen'
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:169: undefined reference to `gzopen'
lib/libhts.a(zfio.o): In function `zfclose':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:180: undefined reference to `gzclose'
lib/libhts.a(zfio.o): In function `zfgets':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:69: undefined reference to `gzgets'
lib/libhts.a(zfio.o): In function `zfeof':
/projects/temp/GTC/htslib-1.3.2/cram/zfio.c:105: undefined reference to `gzeof'
lib/libhts.a(bgzf.o): In function `bgzf_write_init':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:209: undefined reference to `deflateInit2_'
lib/libhts.a(bgzf.o): In function `inflate_gzip_block':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:451: undefined reference to `inflate'
lib/libhts.a(bgzf.o): In function `bgzf_open':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:237: undefined reference to `compressBound'
lib/libhts.a(bgzf.o): In function `bgzf_dopen':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:260: undefined reference to `compressBound'
lib/libhts.a(bgzf.o): In function `bgzf_hopen':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:283: undefined reference to `compressBound'
lib/libhts.a(bgzf.o): In function `bgzf_compress':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:311: undefined reference to `deflateInit2_'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:319: undefined reference to `deflate'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:326: undefined reference to `deflateEnd'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:338: undefined reference to `crc32'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:338: undefined reference to `crc32'
lib/libhts.a(bgzf.o): In function `bgzf_gzip_compress':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:353: undefined reference to `deflate'
lib/libhts.a(bgzf.o): In function `bgzf_mt':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:807: undefined reference to `pthread_create'
lib/libhts.a(bgzf.o): In function `inflate_block':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:399: undefined reference to `inflateInit2_'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:408: undefined reference to `inflate'
/projects/temp/GTC/htslib-1.3.2/bgzf.c:422: undefined reference to `inflateEnd'
lib/libhts.a(bgzf.o): In function `bgzf_read_block':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:634: undefined reference to `inflateInit2_'
lib/libhts.a(bgzf.o): In function `inflate_block':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:413: undefined reference to `inflateEnd'
lib/libhts.a(bgzf.o): In function `bgzf_close':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:983: undefined reference to `deflateEnd'
lib/libhts.a(bgzf.o): In function `mt_destroy':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:820: undefined reference to `pthread_join'
lib/libhts.a(bgzf.o): In function `bgzf_close':
/projects/temp/GTC/htslib-1.3.2/bgzf.c:982: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
makefile:53: recipe for target 'gtc' failed
make: *** [gtc] Error 1

**Comment by agnieszkadanek** [comment]
Hi, Which version of `g++` are you using? (` g++ -v`)

**Comment by raonyguimaraes** [comment]
Hi Agnieszka,

g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 

You guys could provide a DockerFile just to make sure it will work in any machine.

How can I help you to troubleshoot this? Which version of g++ do you want me to try?

**Comment by agnieszkadanek** [comment]
Apparently there is an issue with linking zlib library in some cases. A reordering in the last command should fix the issue:
```
g++ -o gtc src/bit_memory.o src/block_init_compressor.o src/buffered_bm.o src/compressed_pack.o src/compression_settings.o src/decompressor.o src/end_compressor.o src/huffman.o src/main.o src/my_vcf.o src/samples.o src/VCFManager.o include/cpp-mmf/memory_mapped_file.o lib/libhts.a lib/libsdsl.a -O3 -lm -std=c++11 -lpthread -mpopcnt -lz
```
I have also changed the makefile, so you can also try to build GTC from scratch. 

Please let me know if it works for you now.

DockerFile is a good idea, we will definitely consider preparing it.

**Comment by raonyguimaraes** [comment]
make
g++       -Wall -O3 -m64 -std=c++11 -pthread -I include -mpopcnt  -msse4.2 -c src/compressed_pack.cpp -o src/compressed_pack.o
In file included from src/compressed_pack.cpp:10:0:
src/compressed_pack.h:16:10: fatal error: sdsl/bit_vectors.hpp: No such file or directory
 #include <sdsl/bit_vectors.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
makefile:38: recipe for target 'src/compressed_pack.o' failed
make: *** [src/compressed_pack.o] Error 1

**Comment by raonyguimaraes** [comment]
Thank you! That solved the problem :+1:
