### ISSUE TITLE
GTC compile error

### ISSUE THREAD

**Issue by no7ren** [refresh-bio/GTC#5]
I am trying to install GTC but it always complains about the missing libsdsl.a file:
g++: error: lib/libsdsl.a: No such file or directory

I checked the sdsl-lite and sdsl git repo and they both seem to stop having libsdsl.a file after the installation. Can you take a look at it?

**Comment by agnieszkadanek** [comment]
The SDSL library seems to install just fine. Is it possible that you are not meeting some requirements for the SDSL library (and GTC)? Are there any errors during installation of SDSL?

I added a Dockerfile (and a corresponding Dockerfile section in the README), please take a look. It may give you a hint on some dependencies that you are missing.
