### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by lyd0527** [refresh-bio/GTC#7]
Hi,

When I performed GTC, I got an error. Could you pls give me some favor?

Thx,

Yuanda

--------------------------------------------------

File with list of samples (archive.ind) created.
0 variants preprocessed
100000 variants preprocessed
200000 variants preprocessed
300000 variants preprocessed
500000 variants preprocessed
700000 variants preprocessed
800000 variants preprocessed
*** Error in `gtc': malloc(): memory corruption: 0x000000000125c7d0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x82c96)[0x7f1cc440ec96]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f1cc44111ac]
gtc[0x454aab]
gtc[0x43b62a]
gtc[0x431f6d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f1cc43ae3d5]
gtc[0x407cad]

**Comment by agnieszkadanek** [comment]
Could you please provide an example input VCF file to reproduce the error?

**Comment by lyd0527** [comment]
After splitting into pieces, I have found the error position.

```
1	7415546	.	ATCTAAGAGCATCTCCAAGAGACTATCTAAATAGCTTGTCAAACTAAATTTTAGCTACTTAATAACATAATAGCTCTCCAACAGACTAGCCATTTAACTTGCTAAGCTATCTGGCTCTCTAAATTAACTCTCTCATTAGCCAAATTTGGCTACCAACTCTCGCTAGCCAAGCTA
ACTTGCATGTTGGAGAGTCTGTTGGAATGAGATGTTATATATAGAGTTTAATATTTATGGAGAGACAAATAAAGAGTCAAATAGAGAGTTAAAAATAAAGAGTCTCTTGAAGATGC	AATCTGGCTCTCTAAATTAACTCTCTCATTAGCCAAATTTGGCTACCAACTCTCGCTAGCCAAGCTAACTTGCATGTT
GGAGAGTCTGTTGGAATGAGATGTTATATATAGAGTTTAATATTTATGGAGAGACAAATAAAGAGTCAAATAGAGAGTTAAAAATAAAGAGTCTCTTGAAGATGC,A	1852.47	.	AC=11,3;AF=0.024,0.007;AN=454;BaseQRankSum=0.135;ClippingRankSum=0.000
;DP=4223;ExcessHet=0.0000;FS=1.587;InbreedingCoeff=0.2153;MLEAC=8,3;MLEAF=0.018,0.007;MQ=32.35;MQRankSum=0.849;QD=24.37;ReadPosRankSum=0.000;SOR=0.730	GT:AD:DP:GQ:PGT:PID:PL	0/0:11,0,0:11:30:.:.:0
,30,450,30,450,450	./.:0,0,0:0:.:.:.:.
```

**Comment by agnieszkadanek** [comment]
I fixed a bug that could cause the problem. Please let me know if this resolves your issue. 

Just a note: the piece above contains four new line characters that should not be present in a variant description, but I assumed it is a single line in your input VCF.

Is your input VCF publicly available for download? If so, that would help me track the error.

**Comment by lyd0527** [comment]
Thank you very much. After updating, the compressing process was successful.
