### ISSUE TITLE
Cant compress nonhuman dataset

### ISSUE THREAD

**Issue by SmDonkey** [refresh-bio/GTC#8]
hi , 
     When i use gtc to comress the nonhuman dataset
    ( DGRP freeze 2 ftp://ftp.hgsc.bcm.edu/DGRP/freeze2_Feb_2013/vcf_files/freeze2.vcf.gz), it cant work.Error reasons:

File with list of samples (test.ind) created.
[W::vcf_parse] contig 'd8' is not defined in the header. (Quick workaround: index the file with tabix.)
Repair VCF file

**Comment by agnieszkadanek** [comment]
It is an error occurring during parsing the VCF file by the HTSlib. The VCF file should be repaired. As mentioned in the error message, the contig "d8" is apparently not defined in the header.
Index the file with tabix or repair the VCF file adding the contig description, for example:
##contig=<ID=c8,length=62435964>

See VCF Specification for more info:
https://samtools.github.io/hts-specs/VCFv4.3.pdf
